# SWeat 수원외고 1주차 강의노트 (25.08.21)

SWeat 수원외고 1주차에 배운 예제를 실습해봅시다.

## 0. 실습 준비

In [ ]:
# 이 코드는 최초 한 번만 실행해주면 됩니다.
!pip install numpy pandas matplotlib

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [29]:
import pandas as pd
pd.__version__

'2.2.2'

## 1. Numpy 기초

Numpy는 리스트와 비슷하면서도, 숫자 데이터들을 훨씬 빠르고 효율적으로 처리할 수 있게 해주는 도구입니다. 특히 각종 통계처리, 연산 등에서 매우 유용하게 사용할 수 있습니다.

### 1. NumPy 배열 생성

In [ ]:
# 기본 배열 생성
A = np.array([1, 2, 3])

A        # Jupyter Notebook에서는 맨 아래줄에 변수 이름만 써주면, print가 없어도 그 변수의 내용을 출력해줍니다.

array([1, 2, 3])

In [ ]:
# 다차원 배열 생성
B = np.array([[1, 2, 3], [4, 5, 6]])
C = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

B.shape   # .shape를 변수 뒤에 붙여주면 행과 열을 튜플 형태로 표시해줍니다. (2, 3)이면 행 2개, 열 3개로 구성된 array 변수입니다. 

(2, 3)

### 2. NumPy 배열 연산

In [10]:
A = np.array([10, 20, 30])
B = np.array([2, 4, 3])

print("A:", A)
print("B:", B)

print("A + B =", A + B)
print("A - B =", A - B)
print("A * B =", A * B)     # 벡터의 같은 위치의 원소끼리 곱해줍니다.
print("A / B =", A / B)
print("A @ B =", A @ B)     # 행렬곱으로, (10 * 2) + (20 * 4) + (30 * 3)과 같습니다.

print("최솟값:", A.min())
print("최댓값:", A.max())
print("합계:", A.sum())
print("평균:", A.mean())

A: [10 20 30]
B: [2 4 3]
A + B = [12 24 33]
A - B = [ 8 16 27]
A * B = [20 80 90]
A / B = [ 5.  5. 10.]
A @ B = 190
최솟값: 10
최댓값: 30
합계: 60
평균: 20.0


### 3. NumPy 인덱싱과 슬라이싱

In [ ]:
# 전반적으로 파이썬의 리스트와 거의 동일합니다.
# [1:4]면, 마지막 4를 제외한 1,2,3만 포함되는거 기억나시나요?

C = np.array([[1, 2, 3], [4, 5, 6]])

print("C 전체:\n", C)
print("첫 번째 행:", C[0])
print("두 번째 행:", C[1])
print("첫 번째 열:", C[:,0])       # [:,0]에서 앞에 :는 모든 행에서, 뒤에 0은 0번째 열만 뽑아낸다고 생각하면 돼요.
print("2~3열:", C[:,1:3])        # [:, 1:3]에서 앞에 있는 :는 모든 행에서, 뒤에 1:3은 1,2번 열만 뽑아낸다고 생각하면 돼요.


C 전체:
 [[1 2 3]
 [4 5 6]]
첫 번째 행: [1 2 3]
두 번째 행: [4 5 6]
첫 번째 열: [1 4]
2~3열: [[2 3]
 [5 6]]


### 4. 다양한 NumPy 함수

In [ ]:
# 절대 다 외울 필요 없어요! 쓰다가 모르는건 그때그때 찾아서 쓰고, 이런게 있다만 알고 넘어가도 충분합니다.

# 일정 간격 배열 만들기
print("0~10까지 간격 2씩 만든 배열 : ", np.arange(0, 10, 2))
print("0~10까지 4개의 간격으로 만든 배열 : ", np.linspace(0, 12, 4))

# 0과 1로 채운 배열
print("2*2 행렬 만들고 0으로 모두 채우기 :\n", np.zeros((2,2)))
print("2*3 행렬 만들고 1로 모두 채우기 :\n", np.ones((2,3)))

# 난수 배열
print("2*4 행렬 만들고 0~1 랜덤값으로 채우기 :\n", np.random.random((2,4)))

# 표준정규분포 난수
print("표준정규분포에서 10개를 추출한 행렬 만들기", np.random.randn(10))


0~10까지 간격 2씩 만든 배열 :  [0 2 4 6 8]
0~10까지 4개의 간격으로 만든 배열 :  [ 0.  4.  8. 12.]
2*2 행렬 만들고 0으로 모두 채우기 :
 [[0. 0.]
 [0. 0.]]
2*3 행렬 만들고 1로 모두 채우기 :
 [[1. 1. 1.]
 [1. 1. 1.]]
2*4 행렬 만들고 0~1 랜덤값으로 채우기 :
 [[0.91828245 0.95393677 0.98706775 0.21920695]
 [0.371016   0.13259053 0.12270788 0.20029741]]
표준정규분포에서 10개를 추출한 행렬 만들기 [-1.31254056 -0.38678239 -0.36408176 -0.16421758 -0.48440064  0.86514466
 -0.46895504 -1.69992603 -0.32941465  0.98212558]


## 2. Pandas 기초

Numpy는 숫자 데이터를 담은 행렬을 다루는 라이브러리였다면, Pandas는 마치 엑셀같이 DataFrame이라는 자료형의 표 데이터를 다루는 라이브러리입니다. 각종 데이터 정제 및 표현은 물론, 통계적 연산과 필터링 등 강력한 기능들을 효율적으로 실행할 수 있습니다.

In [33]:
# ⚠️ 컴퓨터에서 바로 실행한다면 이 코드로 실행하세요. read_csv(<파일 경로>)로 넣으면 됩니다.
df = pd.read_csv('/Users/chungheelee/Downloads/villagers.csv')

print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


이름 성별       생일   종류       성격 일어나는 시각 잠드는 시각    자금  가구 수
0     럭키  남  11월 04일    개       먹보    8:00  23:00  5575     2
1     로빈  남  05월 13일    개       먹보    8:00  23:00  2703     5
2      존  남  11월 01일    개      무뚝뚝    9:00   3:30  9850     1
3     토미  남  08월 04일    개       먹보    8:00  23:00  3665     2
4      벤  남  06월 10일    개       먹보    8:00  23:00  6994     3
..   ... ..      ...  ...      ...     ...    ...   ...   ...
408  고메스  남  08월 26일  호랑이  무뚝뚝/운동광     NaN    NaN  7733     8
409   범호  남  05월 15일  호랑이      운동광    6:30   0:30  6865     2
410   루주  여  08월 27일  호랑이      아이돌    7:30   1:30  1658     9
411   백희  여  12월 13일  호랑이      아이돌    7:30   1:30  5056     9
412   신디  여  11월 22일  호랑이      성숙함    8:30   2:30  3784     8

[413 rows x 9 columns]

In [ ]:
# ⚠️ Colab 상에서 실행한다면 이 블럭을 실행하고, 첨부파일로 직접 villagers.csv 파일을 업로드하세요.
from google.colab import files
df = files.upload()

print(type(df))
df

### 1. 기본 정보 확인

In [ ]:
# 데이터의 위에서 N개, 아래에서 N개만 확인할 때
print("상위 5개 데이터 : \n", df.head())
print("하위 7개 데이터 : \n", df.tail(7))

# Numpy처럼 shape을 쓰면 행과 열 개수 확인 가능
print("주민 데이터 크기 : ", df.shape)

# Column (속성)에 무엇이 있었는지만 확인
print("주민 정보 종류 : ", df.columns)

# Column별 자료형 확인
print("정보 별 자료형 : \n", df.dtypes)

# 전체 DataFrame의 정보
print("전체 정보 : \n", df.info())

상위 5개 데이터 : 
    이름 성별       생일 종류   성격 일어나는 시각 잠드는 시각    자금  가구 수
0  럭키  남  11월 04일  개   먹보    8:00  23:00  5575     2
1  로빈  남  05월 13일  개   먹보    8:00  23:00  2703     5
2   존  남  11월 01일  개  무뚝뚝    9:00   3:30  9850     1
3  토미  남  08월 04일  개   먹보    8:00  23:00  3665     2
4   벤  남  06월 10일  개   먹보    8:00  23:00  6994     3
하위 7개 데이터 : 
       이름 성별       생일   종류       성격 일어나는 시각 잠드는 시각    자금  가구 수
406  호랭이  남  08월 22일  호랑이      무뚝뚝    9:00   3:30  8000     2
407  티볼트  남  08월 19일  호랑이      운동광    6:30   0:30  1361     1
408  고메스  남  08월 26일  호랑이  무뚝뚝/운동광     NaN    NaN  7733     8
409   범호  남  05월 15일  호랑이      운동광    6:30   0:30  6865     2
410   루주  여  08월 27일  호랑이      아이돌    7:30   1:30  1658     9
411   백희  여  12월 13일  호랑이      아이돌    7:30   1:30  5056     9
412   신디  여  11월 22일  호랑이      성숙함    8:30   2:30  3784     8
주민 데이터 크기 :  (413, 9)
주민 정보 종류 :  Index(['이름', '성별', '생일', '종류', '성격', '일어나는 시각', '잠드는 시각', '자금', '가구 수'], dtype='object')
정보 별 자료형 : 
 이름         object
성별  

### 2. 데이터 추출

In [44]:
# 특정 열 추출 (여러 개를 추출할때는 괄호 두 번 써주세요)
bday = df['생일']
bday.head()

0    11월 04일
1    05월 13일
2    11월 01일
3    08월 04일
4    06월 10일
Name: 생일, dtype: object

In [45]:
# 다중 열 추출 (여러 개를 추출할때는 괄호 두 번 써주세요)
name_and_bday = df[['이름', '생일']]
name_and_bday.head()

이름       생일
0  럭키  11월 04일
1  로빈  05월 13일
2   존  11월 01일
3  토미  08월 04일
4   벤  06월 10일

In [ ]:
# 특정 행 추출 (위에서부터 N번째 주민의 정보를 알고 싶을 때)
apple = df.loc[405]     # 위의 방법은 열을 추출했다면, 이 방법은 405번째 줄의 정보를 가져옴
apple

이름              애플
성별               여
생일         09월 24일
종류             햄스터
성격             아이돌
일어나는 시각       7:30
잠드는 시각        1:30
자금            7390
가구 수            10
Name: 405, dtype: object

In [48]:
# 여러 행 추출도 괄호 두번 사용
animals = df.loc[[61, 122, 405]]
animals

이름 성별       생일   종류   성격 일어나는 시각 잠드는 시각    자금  가구 수
61   잭슨  남  10월 01일  고양이  느끼함    7:00   2:00  1967     1
122  쭈니  남  09월 29일  다람쥐  느끼함    7:00   2:00  9546     8
405  애플  여  09월 24일  햄스터  아이돌    7:30   1:30  7390    10

### 3. 데이터 그룹화 및 통계

In [67]:
# 만약 남자, 여자 주민의 가진 돈의 평균을 알고 싶다면?
# 먼저 성별로 '주민'을 그룹으로 나누고, 그 안에서 '자금' 열을 골라, '평균'을 계산해볼까요?

df.groupby('성별')['자금'].mean()               # mean은 자금의 평균값을 계산

성별
(없음)    3756.857143
남       5931.971014
여       5198.633166
Name: 자금, dtype: float64

In [ ]:
# 각종 통계량을 계산하는 유용한 함수
print(df['자금'].min())     # 최소값
print(df['자금'].max())     # 최대값
print(df['자금'].sum())     # 합계
print(df['자금'].mean())    # 평균
print(df['자금'].var())     # 분산
print(df['자금'].std())     # 표준편차
print(df['자금'].count())   # 개수 세기
print(df['자금'].median())  # 중앙값 (오름차순으로 했을 때 정중앙의 값)
print(df['자금'].mode())    # 최빈값 (가장 자주 나타난 값)

## 👀 연습문제

### 문제 1. NumPy 기초
1. `arange`, `linspace`을 이용해 1부터 10까지 들어있는 배열을 만들어보세요.
2. 이 배열의 합(`sum`)과 평균(`mean`)을 구해보세요.
3. 모든 원소가 0으로 채워진 3*3 배열을 만들어보세요.
4. `np.random.random()`을 이용해 5*3 크기의 난수 행렬을 만들고, 그 중 첫 번째 열만 출력해보세요.

### 문제 2. Pandas 기초 (villagers.csv 파일 로드)
1. 365번 주민의 정보를 pandas로 구해보세요.
2. 동물의 숲 주민 중 가장 많은 유형의 '성격'은 무엇일까요?
3. 동물의 숲 주민의 동물 '종류'별로 자금의 중앙값을 알고 싶어요. 어떻게 하면 될까요?